// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_auth.sql

package db

import (
	"context"
)

const deleteUserRepositories = `-- name: DeleteUserRepositories :exec
DELETE FROM repositories
WHERE user_id = $1
`

func (q *Queries) DeleteUserRepositories(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRepositories, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, login, name, email, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOAuthToken = `-- name: GetUserOAuthToken :one
SELECT id, user_id, provider, access_token, created_at, updated_at
FROM user_oauth_tokens
WHERE user_id = $1
  AND provider = $2
LIMIT 1
`

type GetUserOAuthTokenParams struct {
	UserID   int64  `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetUserOAuthToken(ctx context.Context, arg GetUserOAuthTokenParams) (UserOauthToken, error) {
	row := q.db.QueryRow(ctx, getUserOAuthToken, arg.UserID, arg.Provider)
	var i UserOauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserRepositories = `-- name: ListUserRepositories :many
SELECT id, user_id, github_repo_id, name, full_name, private, default_branch, html_url, created_at, updated_at
FROM repositories
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListUserRepositories(ctx context.Context, userID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listUserRepositories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GithubRepoID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.DefaultBranch,
			&i.HtmlUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGitHubUser = `-- name: UpsertGitHubUser :one
INSERT INTO users (
    github_id,
    login,
    name,
    email,
    avatar_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (github_id)
DO UPDATE SET
    login = EXCLUDED.login,
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, github_id, login, name, email, avatar_url, created_at, updated_at
`

type UpsertGitHubUserParams struct {
	GithubID  int64  `json:"github_id"`
	Login     string `json:"login"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	AvatarUrl string `json:"avatar_url"`
}

func (q *Queries) UpsertGitHubUser(ctx context.Context, arg UpsertGitHubUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGitHubUser,
		arg.GithubID,
		arg.Login,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :exec
INSERT INTO repositories (
    user_id,
    github_repo_id,
    name,
    full_name,
    private,
    default_branch,
    html_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (user_id, github_repo_id)
DO UPDATE SET
    name = EXCLUDED.name,
    full_name = EXCLUDED.full_name,
    private = EXCLUDED.private,
    default_branch = EXCLUDED.default_branch,
    html_url = EXCLUDED.html_url,
    updated_at = NOW()
`

type UpsertRepositoryParams struct {
	UserID        int64  `json:"user_id"`
	GithubRepoID  int64  `json:"github_repo_id"`
	Name          string `json:"name"`
	FullName      string `json:"full_name"`
	Private       bool   `json:"private"`
	DefaultBranch string `json:"default_branch"`
	HtmlUrl       string `json:"html_url"`
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error {
	_, err := q.db.Exec(ctx, upsertRepository,
		arg.UserID,
		arg.GithubRepoID,
		arg.Name,
		arg.FullName,
		arg.Private,
		arg.DefaultBranch,
		arg.HtmlUrl,
	)
	return err
}

const upsertUserOAuthToken = `-- name: UpsertUserOAuthToken :exec
INSERT INTO user_oauth_tokens (
    user_id,
    provider,
    access_token
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (user_id, provider)
DO UPDATE SET
    access_token = EXCLUDED.access_token,
    updated_at = NOW()
`

type UpsertUserOAuthTokenParams struct {
	UserID      int64  `json:"user_id"`
	Provider    string `json:"provider"`
	AccessToken string `json:"access_token"`
}

func (q *Queries) UpsertUserOAuthToken(ctx context.Context, arg UpsertUserOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, upsertUserOAuthToken, arg.UserID, arg.Provider, arg.AccessToken)
	return err
}
