// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegrationActivity = `-- name: CreateIntegrationActivity :exec
INSERT INTO integration_activities (
    user_id,
    integration_id,
    provider,
    action,
    status,
    detail,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateIntegrationActivityParams struct {
	UserID        int64       `json:"user_id"`
	IntegrationID pgtype.Int8 `json:"integration_id"`
	Provider      string      `json:"provider"`
	Action        string      `json:"action"`
	Status        string      `json:"status"`
	Detail        string      `json:"detail"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateIntegrationActivity(ctx context.Context, arg CreateIntegrationActivityParams) error {
	_, err := q.db.Exec(ctx, createIntegrationActivity,
		arg.UserID,
		arg.IntegrationID,
		arg.Provider,
		arg.Action,
		arg.Status,
		arg.Detail,
		arg.Metadata,
	)
	return err
}

const getIntegrationByProviderAndUser = `-- name: GetIntegrationByProviderAndUser :one
SELECT id, user_id, provider, name, status, enabled, config, connected_at, last_error, created_at, updated_at
FROM integrations
WHERE user_id = $1
  AND provider = $2
LIMIT 1
`

type GetIntegrationByProviderAndUserParams struct {
	UserID   int64  `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetIntegrationByProviderAndUser(ctx context.Context, arg GetIntegrationByProviderAndUserParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByProviderAndUser, arg.UserID, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Name,
		&i.Status,
		&i.Enabled,
		&i.Config,
		&i.ConnectedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationActivitiesByUser = `-- name: ListIntegrationActivitiesByUser :many
SELECT id, user_id, integration_id, provider, action, status, detail, metadata, created_at
FROM integration_activities
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListIntegrationActivitiesByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIntegrationActivitiesByUser(ctx context.Context, arg ListIntegrationActivitiesByUserParams) ([]IntegrationActivity, error) {
	rows, err := q.db.Query(ctx, listIntegrationActivitiesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationActivity
	for rows.Next() {
		var i IntegrationActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IntegrationID,
			&i.Provider,
			&i.Action,
			&i.Status,
			&i.Detail,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByUser = `-- name: ListIntegrationsByUser :many
SELECT id, user_id, provider, name, status, enabled, config, connected_at, last_error, created_at, updated_at
FROM integrations
WHERE user_id = $1
ORDER BY provider
`

func (q *Queries) ListIntegrationsByUser(ctx context.Context, userID int64) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Name,
			&i.Status,
			&i.Enabled,
			&i.Config,
			&i.ConnectedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationStatus = `-- name: UpdateIntegrationStatus :exec
UPDATE integrations
SET status = $3,
    last_error = $4,
    updated_at = NOW()
WHERE user_id = $1
  AND provider = $2
`

type UpdateIntegrationStatusParams struct {
	UserID    int64  `json:"user_id"`
	Provider  string `json:"provider"`
	Status    string `json:"status"`
	LastError string `json:"last_error"`
}

func (q *Queries) UpdateIntegrationStatus(ctx context.Context, arg UpdateIntegrationStatusParams) error {
	_, err := q.db.Exec(ctx, updateIntegrationStatus,
		arg.UserID,
		arg.Provider,
		arg.Status,
		arg.LastError,
	)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :one
INSERT INTO integrations (
    user_id,
    provider,
    name,
    status,
    enabled,
    config,
    connected_at,
    last_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW(),
    ''
)
ON CONFLICT (user_id, provider)
DO UPDATE SET
    name = EXCLUDED.name,
    status = EXCLUDED.status,
    enabled = EXCLUDED.enabled,
    config = EXCLUDED.config,
    connected_at = NOW(),
    last_error = '',
    updated_at = NOW()
RETURNING id, user_id, provider, name, status, enabled, config, connected_at, last_error, created_at, updated_at
`

type UpsertIntegrationParams struct {
	UserID   int64  `json:"user_id"`
	Provider string `json:"provider"`
	Name     string `json:"name"`
	Status   string `json:"status"`
	Enabled  bool   `json:"enabled"`
	Config   []byte `json:"config"`
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, upsertIntegration,
		arg.UserID,
		arg.Provider,
		arg.Name,
		arg.Status,
		arg.Enabled,
		arg.Config,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Name,
		&i.Status,
		&i.Enabled,
		&i.Config,
		&i.ConnectedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
