// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CustomSourceFormat string

const (
	CustomSourceFormatOsv CustomSourceFormat = "osv"
	CustomSourceFormatNvd CustomSourceFormat = "nvd"
)

func (e *CustomSourceFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomSourceFormat(s)
	case string:
		*e = CustomSourceFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomSourceFormat: %T", src)
	}
	return nil
}

type NullCustomSourceFormat struct {
	CustomSourceFormat CustomSourceFormat `json:"custom_source_format"`
	Valid              bool               `json:"valid"` // Valid is true if CustomSourceFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomSourceFormat) Scan(value interface{}) error {
	if value == nil {
		ns.CustomSourceFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomSourceFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomSourceFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomSourceFormat), nil
}

type Severity string

const (
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

func (e *Severity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Severity(s)
	case string:
		*e = Severity(s)
	default:
		return fmt.Errorf("unsupported scan type for Severity: %T", src)
	}
	return nil
}

type NullSeverity struct {
	Severity Severity `json:"severity"`
	Valid    bool     `json:"valid"` // Valid is true if Severity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.Severity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Severity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Severity), nil
}

type TriggerType string

const (
	TriggerTypePush        TriggerType = "push"
	TriggerTypePullRequest TriggerType = "pull_request"
	TriggerTypeSchedule    TriggerType = "schedule"
	TriggerTypeManual      TriggerType = "manual"
)

func (e *TriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerType(s)
	case string:
		*e = TriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerType: %T", src)
	}
	return nil
}

type NullTriggerType struct {
	TriggerType TriggerType `json:"trigger_type"`
	Valid       bool        `json:"valid"` // Valid is true if TriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerType), nil
}

type CustomDomain struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	Hostname          string             `json:"hostname"`
	Status            string             `json:"status"`
	VerificationToken string             `json:"verification_token"`
	DnsRecordType     string             `json:"dns_record_type"`
	DnsRecordName     string             `json:"dns_record_name"`
	DnsRecordValue    string             `json:"dns_record_value"`
	LastError         string             `json:"last_error"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DependencyPackage struct {
	ID             int64              `json:"id"`
	Manager        string             `json:"manager"`
	Registry       string             `json:"registry"`
	NormalizedName string             `json:"normalized_name"`
	DisplayName    string             `json:"display_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DependencyPackageVersion struct {
	ID            int64              `json:"id"`
	PackageID     int64              `json:"package_id"`
	Version       string             `json:"version"`
	Creator       string             `json:"creator"`
	Description   string             `json:"description"`
	License       string             `json:"license"`
	Homepage      string             `json:"homepage"`
	RepositoryUrl string             `json:"repository_url"`
	RegistryUrl   string             `json:"registry_url"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DependencyVersionDependency struct {
	ID             int64              `json:"id"`
	FromVersionID  int64              `json:"from_version_id"`
	ToVersionID    int64              `json:"to_version_id"`
	DependencyType string             `json:"dependency_type"`
	VersionSpec    string             `json:"version_spec"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Integration struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Provider    string             `json:"provider"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	Enabled     bool               `json:"enabled"`
	Config      []byte             `json:"config"`
	ConnectedAt pgtype.Timestamptz `json:"connected_at"`
	LastError   string             `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationActivity struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	IntegrationID pgtype.Int8        `json:"integration_id"`
	Provider      string             `json:"provider"`
	Action        string             `json:"action"`
	Status        string             `json:"status"`
	Detail        string             `json:"detail"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Policy struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PolicyRegistry struct {
	PolicyID          int64    `json:"policy_id"`
	PushEnabled       bool     `json:"push_enabled"`
	PushUrl           string   `json:"push_url"`
	PushSigningKeyRef string   `json:"push_signing_key_ref"`
	PullEnabled       bool     `json:"pull_enabled"`
	PullUrl           string   `json:"pull_url"`
	PullTrustedKeys   []string `json:"pull_trusted_keys"`
	PullMaxAgeDays    int32    `json:"pull_max_age_days"`
}

type PolicyRepository struct {
	RepositoryID int64              `json:"repository_id"`
	PolicyID     int64              `json:"policy_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
}

type PolicySast struct {
	PolicyID          int64    `json:"policy_id"`
	Enabled           bool     `json:"enabled"`
	PatternsEnabled   bool     `json:"patterns_enabled"`
	Rulesets          []string `json:"rulesets"`
	MinSeverity       Severity `json:"min_severity"`
	ExcludePaths      []string `json:"exclude_paths"`
	AiEnabled         bool     `json:"ai_enabled"`
	AiMaxFilesPerScan int32    `json:"ai_max_files_per_scan"`
	AiReachability    bool     `json:"ai_reachability"`
	AiSuggestFix      bool     `json:"ai_suggest_fix"`
}

type PolicySource struct {
	PolicyID           int64  `json:"policy_id"`
	RegistryFirst      bool   `json:"registry_first"`
	RegistryMaxAgeDays int32  `json:"registry_max_age_days"`
	RegistryOnly       bool   `json:"registry_only"`
	OsvEnabled         bool   `json:"osv_enabled"`
	GhsaEnabled        bool   `json:"ghsa_enabled"`
	GhsaTokenRef       string `json:"ghsa_token_ref"`
	NvdEnabled         bool   `json:"nvd_enabled"`
	NvdApiKeyRef       string `json:"nvd_api_key_ref"`
	GovulncheckEnabled bool   `json:"govulncheck_enabled"`
	SupplyChainEnabled bool   `json:"supply_chain_enabled"`
}

type PolicySourceCustom struct {
	ID         int64              `json:"id"`
	PolicyID   int64              `json:"policy_id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Format     CustomSourceFormat `json:"format"`
	AuthHeader string             `json:"auth_header"`
}

type PolicyTrigger struct {
	ID        int64              `json:"id"`
	PolicyID  int64              `json:"policy_id"`
	Type      TriggerType        `json:"type"`
	Branches  []string           `json:"branches"`
	Cron      pgtype.Text        `json:"cron"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	GithubRepoID  int64              `json:"github_repo_id"`
	Name          string             `json:"name"`
	FullName      string             `json:"full_name"`
	Private       bool               `json:"private"`
	DefaultBranch string             `json:"default_branch"`
	HtmlUrl       string             `json:"html_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryDependency struct {
	ID                int64              `json:"id"`
	RepositoryID      int64              `json:"repository_id"`
	PackageID         int64              `json:"package_id"`
	SourceFile        string             `json:"source_file"`
	Scope             string             `json:"scope"`
	VersionSpec       string             `json:"version_spec"`
	ResolvedVersionID pgtype.Int8        `json:"resolved_version_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryDependencyFile struct {
	ID           int64              `json:"id"`
	RepositoryID int64              `json:"repository_id"`
	Path         string             `json:"path"`
	File         string             `json:"file"`
	Manager      string             `json:"manager"`
	Registry     string             `json:"registry"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryDependencySync struct {
	ID           int64              `json:"id"`
	RepositoryID int64              `json:"repository_id"`
	Status       string             `json:"status"`
	Trigger      string             `json:"trigger"`
	ErrorMessage string             `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryFindingOccurrence struct {
	RepositoryID int64              `json:"repository_id"`
	FindingID    int64              `json:"finding_id"`
	Status       string             `json:"status"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryScanFinding struct {
	ID              int64              `json:"id"`
	ScanRunID       int64              `json:"scan_run_id"`
	RepositoryID    int64              `json:"repository_id"`
	PolicyID        pgtype.Int8        `json:"policy_id"`
	PackageID       pgtype.Int8        `json:"package_id"`
	PackageName     string             `json:"package_name"`
	Manager         string             `json:"manager"`
	Registry        string             `json:"registry"`
	VersionSpec     string             `json:"version_spec"`
	ResolvedVersion string             `json:"resolved_version"`
	AdvisoryID      string             `json:"advisory_id"`
	Aliases         []string           `json:"aliases"`
	Title           string             `json:"title"`
	Summary         string             `json:"summary"`
	Severity        Severity           `json:"severity"`
	FixedVersion    string             `json:"fixed_version"`
	ReferenceUrl    string             `json:"reference_url"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryScanFindingSource struct {
	FindingID        int64              `json:"finding_id"`
	Source           string             `json:"source"`
	ProviderRecordID string             `json:"provider_record_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RepositoryScanLog struct {
	ID            int64              `json:"id"`
	ScanRunID     int64              `json:"scan_run_id"`
	RepositoryID  int64              `json:"repository_id"`
	Level         string             `json:"level"`
	Message       string             `json:"message"`
	DirectoryPath string             `json:"directory_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RepositoryScanRun struct {
	ID               int64              `json:"id"`
	RepositoryID     int64              `json:"repository_id"`
	PolicyID         pgtype.Int8        `json:"policy_id"`
	Trigger          string             `json:"trigger"`
	Status           string             `json:"status"`
	ErrorMessage     string             `json:"error_message"`
	FindingsTotal    int32              `json:"findings_total"`
	FindingsCritical int32              `json:"findings_critical"`
	FindingsHigh     int32              `json:"findings_high"`
	FindingsMedium   int32              `json:"findings_medium"`
	FindingsLow      int32              `json:"findings_low"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryScanRunFinding struct {
	ScanRunID int64              `json:"scan_run_id"`
	FindingID int64              `json:"finding_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ServiceStatusSnapshot struct {
	ID        int64              `json:"id"`
	Service   string             `json:"service"`
	Status    string             `json:"status"`
	LatencyMs int32              `json:"latency_ms"`
	UptimePct float64            `json:"uptime_pct"`
	Note      string             `json:"note"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	GithubID  int64              `json:"github_id"`
	Login     string             `json:"login"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	AvatarUrl string             `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGithubInstallation struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	InstallationID int64              `json:"installation_id"`
	AppSlug        string             `json:"app_slug"`
	AccountLogin   string             `json:"account_login"`
	AccountType    string             `json:"account_type"`
	HtmlUrl        string             `json:"html_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserOauthToken struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Provider    string             `json:"provider"`
	AccessToken string             `json:"access_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
