// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPolicyToRepository = `-- name: AssignPolicyToRepository :exec
INSERT INTO policy_repositories (
    repository_id,
    policy_id,
    assigned_at
) VALUES (
    $1,
    $2,
    NOW()
)
ON CONFLICT (repository_id)
DO UPDATE SET
    policy_id = EXCLUDED.policy_id,
    assigned_at = NOW()
`

type AssignPolicyToRepositoryParams struct {
	RepositoryID int64 `json:"repository_id"`
	PolicyID     int64 `json:"policy_id"`
}

func (q *Queries) AssignPolicyToRepository(ctx context.Context, arg AssignPolicyToRepositoryParams) error {
	_, err := q.db.Exec(ctx, assignPolicyToRepository, arg.RepositoryID, arg.PolicyID)
	return err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (
    user_id,
    name,
    enabled
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, name, enabled, created_at, updated_at
`

type CreatePolicyParams struct {
	UserID  int64  `json:"user_id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, createPolicy, arg.UserID, arg.Name, arg.Enabled)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolicyCustomSource = `-- name: CreatePolicyCustomSource :exec
INSERT INTO policy_source_custom (
    policy_id,
    name,
    url,
    format,
    auth_header
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreatePolicyCustomSourceParams struct {
	PolicyID   int64              `json:"policy_id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Format     CustomSourceFormat `json:"format"`
	AuthHeader string             `json:"auth_header"`
}

func (q *Queries) CreatePolicyCustomSource(ctx context.Context, arg CreatePolicyCustomSourceParams) error {
	_, err := q.db.Exec(ctx, createPolicyCustomSource,
		arg.PolicyID,
		arg.Name,
		arg.Url,
		arg.Format,
		arg.AuthHeader,
	)
	return err
}

const createPolicyTrigger = `-- name: CreatePolicyTrigger :exec
INSERT INTO policy_triggers (
    policy_id,
    type,
    branches,
    cron,
    timezone
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreatePolicyTriggerParams struct {
	PolicyID int64       `json:"policy_id"`
	Type     TriggerType `json:"type"`
	Branches []string    `json:"branches"`
	Cron     pgtype.Text `json:"cron"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) CreatePolicyTrigger(ctx context.Context, arg CreatePolicyTriggerParams) error {
	_, err := q.db.Exec(ctx, createPolicyTrigger,
		arg.PolicyID,
		arg.Type,
		arg.Branches,
		arg.Cron,
		arg.Timezone,
	)
	return err
}

const deletePolicyByIDAndUser = `-- name: DeletePolicyByIDAndUser :exec
DELETE FROM policies
WHERE id = $1
  AND user_id = $2
`

type DeletePolicyByIDAndUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePolicyByIDAndUser(ctx context.Context, arg DeletePolicyByIDAndUserParams) error {
	_, err := q.db.Exec(ctx, deletePolicyByIDAndUser, arg.ID, arg.UserID)
	return err
}

const deletePolicyCustomSourcesByPolicy = `-- name: DeletePolicyCustomSourcesByPolicy :exec
DELETE FROM policy_source_custom
WHERE policy_id = $1
`

func (q *Queries) DeletePolicyCustomSourcesByPolicy(ctx context.Context, policyID int64) error {
	_, err := q.db.Exec(ctx, deletePolicyCustomSourcesByPolicy, policyID)
	return err
}

const deletePolicyRepositoryAssignmentsByPolicy = `-- name: DeletePolicyRepositoryAssignmentsByPolicy :exec
DELETE FROM policy_repositories
WHERE policy_id = $1
`

func (q *Queries) DeletePolicyRepositoryAssignmentsByPolicy(ctx context.Context, policyID int64) error {
	_, err := q.db.Exec(ctx, deletePolicyRepositoryAssignmentsByPolicy, policyID)
	return err
}

const deletePolicyTriggersByPolicy = `-- name: DeletePolicyTriggersByPolicy :exec
DELETE FROM policy_triggers
WHERE policy_id = $1
`

func (q *Queries) DeletePolicyTriggersByPolicy(ctx context.Context, policyID int64) error {
	_, err := q.db.Exec(ctx, deletePolicyTriggersByPolicy, policyID)
	return err
}

const getPolicyByIDAndUser = `-- name: GetPolicyByIDAndUser :one
SELECT id, user_id, name, enabled, created_at, updated_at
FROM policies
WHERE id = $1
  AND user_id = $2
`

type GetPolicyByIDAndUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetPolicyByIDAndUser(ctx context.Context, arg GetPolicyByIDAndUserParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByIDAndUser, arg.ID, arg.UserID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyRegistryByPolicy = `-- name: GetPolicyRegistryByPolicy :one
SELECT
    policy_id,
    push_enabled,
    push_url,
    push_signing_key_ref,
    pull_enabled,
    pull_url,
    pull_trusted_keys,
    pull_max_age_days
FROM policy_registry
WHERE policy_id = $1
`

func (q *Queries) GetPolicyRegistryByPolicy(ctx context.Context, policyID int64) (PolicyRegistry, error) {
	row := q.db.QueryRow(ctx, getPolicyRegistryByPolicy, policyID)
	var i PolicyRegistry
	err := row.Scan(
		&i.PolicyID,
		&i.PushEnabled,
		&i.PushUrl,
		&i.PushSigningKeyRef,
		&i.PullEnabled,
		&i.PullUrl,
		&i.PullTrustedKeys,
		&i.PullMaxAgeDays,
	)
	return i, err
}

const getPolicySastByPolicy = `-- name: GetPolicySastByPolicy :one
SELECT
    policy_id,
    enabled,
    patterns_enabled,
    rulesets,
    min_severity,
    exclude_paths,
    ai_enabled,
    ai_max_files_per_scan,
    ai_reachability,
    ai_suggest_fix
FROM policy_sast
WHERE policy_id = $1
`

func (q *Queries) GetPolicySastByPolicy(ctx context.Context, policyID int64) (PolicySast, error) {
	row := q.db.QueryRow(ctx, getPolicySastByPolicy, policyID)
	var i PolicySast
	err := row.Scan(
		&i.PolicyID,
		&i.Enabled,
		&i.PatternsEnabled,
		&i.Rulesets,
		&i.MinSeverity,
		&i.ExcludePaths,
		&i.AiEnabled,
		&i.AiMaxFilesPerScan,
		&i.AiReachability,
		&i.AiSuggestFix,
	)
	return i, err
}

const getPolicySourcesByPolicy = `-- name: GetPolicySourcesByPolicy :one
SELECT
    policy_id,
    registry_first,
    registry_max_age_days,
    registry_only,
    osv_enabled,
    ghsa_enabled,
    ghsa_token_ref,
    nvd_enabled,
    nvd_api_key_ref,
    govulncheck_enabled,
    supply_chain_enabled
FROM policy_sources
WHERE policy_id = $1
`

func (q *Queries) GetPolicySourcesByPolicy(ctx context.Context, policyID int64) (PolicySource, error) {
	row := q.db.QueryRow(ctx, getPolicySourcesByPolicy, policyID)
	var i PolicySource
	err := row.Scan(
		&i.PolicyID,
		&i.RegistryFirst,
		&i.RegistryMaxAgeDays,
		&i.RegistryOnly,
		&i.OsvEnabled,
		&i.GhsaEnabled,
		&i.GhsaTokenRef,
		&i.NvdEnabled,
		&i.NvdApiKeyRef,
		&i.GovulncheckEnabled,
		&i.SupplyChainEnabled,
	)
	return i, err
}

const getRepositoryPolicyByGitHubRepoIDAndUser = `-- name: GetRepositoryPolicyByGitHubRepoIDAndUser :one
SELECT p.id, p.user_id, p.name, p.enabled, p.created_at, p.updated_at
FROM policy_repositories pr
INNER JOIN repositories r ON r.id = pr.repository_id
INNER JOIN policies p ON p.id = pr.policy_id
WHERE r.user_id = $1
  AND r.github_repo_id = $2
`

type GetRepositoryPolicyByGitHubRepoIDAndUserParams struct {
	UserID       int64 `json:"user_id"`
	GithubRepoID int64 `json:"github_repo_id"`
}

func (q *Queries) GetRepositoryPolicyByGitHubRepoIDAndUser(ctx context.Context, arg GetRepositoryPolicyByGitHubRepoIDAndUserParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getRepositoryPolicyByGitHubRepoIDAndUser, arg.UserID, arg.GithubRepoID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRepositoryByGitHubRepoID = `-- name: GetUserRepositoryByGitHubRepoID :one
SELECT id, user_id, github_repo_id, name, full_name, private, default_branch, html_url, created_at, updated_at
FROM repositories
WHERE user_id = $1
  AND github_repo_id = $2
`

type GetUserRepositoryByGitHubRepoIDParams struct {
	UserID       int64 `json:"user_id"`
	GithubRepoID int64 `json:"github_repo_id"`
}

func (q *Queries) GetUserRepositoryByGitHubRepoID(ctx context.Context, arg GetUserRepositoryByGitHubRepoIDParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getUserRepositoryByGitHubRepoID, arg.UserID, arg.GithubRepoID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubRepoID,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.DefaultBranch,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPoliciesByUser = `-- name: ListPoliciesByUser :many
SELECT
    p.id,
    p.user_id,
    p.name,
    p.enabled,
    p.created_at,
    p.updated_at,
    COUNT(pr.repository_id)::BIGINT AS repository_count
FROM policies p
LEFT JOIN policy_repositories pr ON pr.policy_id = p.id
LEFT JOIN repositories r ON r.id = pr.repository_id AND r.user_id = p.user_id
WHERE p.user_id = $1
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPoliciesByUserRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Name            string             `json:"name"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RepositoryCount int64              `json:"repository_count"`
}

func (q *Queries) ListPoliciesByUser(ctx context.Context, userID int64) ([]ListPoliciesByUserRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesByUserRow
	for rows.Next() {
		var i ListPoliciesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyCustomSourcesByPolicy = `-- name: ListPolicyCustomSourcesByPolicy :many
SELECT id, policy_id, name, url, format, auth_header
FROM policy_source_custom
WHERE policy_id = $1
ORDER BY id
`

func (q *Queries) ListPolicyCustomSourcesByPolicy(ctx context.Context, policyID int64) ([]PolicySourceCustom, error) {
	rows, err := q.db.Query(ctx, listPolicyCustomSourcesByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicySourceCustom
	for rows.Next() {
		var i PolicySourceCustom
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Name,
			&i.Url,
			&i.Format,
			&i.AuthHeader,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyRepositoriesByPolicyAndUser = `-- name: ListPolicyRepositoriesByPolicyAndUser :many
SELECT
    r.id,
    r.github_repo_id,
    r.full_name,
    pr.assigned_at
FROM policy_repositories pr
INNER JOIN repositories r ON r.id = pr.repository_id
WHERE pr.policy_id = $1
  AND r.user_id = $2
ORDER BY r.full_name
`

type ListPolicyRepositoriesByPolicyAndUserParams struct {
	PolicyID int64 `json:"policy_id"`
	UserID   int64 `json:"user_id"`
}

type ListPolicyRepositoriesByPolicyAndUserRow struct {
	ID           int64              `json:"id"`
	GithubRepoID int64              `json:"github_repo_id"`
	FullName     string             `json:"full_name"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListPolicyRepositoriesByPolicyAndUser(ctx context.Context, arg ListPolicyRepositoriesByPolicyAndUserParams) ([]ListPolicyRepositoriesByPolicyAndUserRow, error) {
	rows, err := q.db.Query(ctx, listPolicyRepositoriesByPolicyAndUser, arg.PolicyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyRepositoriesByPolicyAndUserRow
	for rows.Next() {
		var i ListPolicyRepositoriesByPolicyAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubRepoID,
			&i.FullName,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyTriggersByPolicy = `-- name: ListPolicyTriggersByPolicy :many
SELECT id, policy_id, type, branches, cron, timezone, created_at
FROM policy_triggers
WHERE policy_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPolicyTriggersByPolicy(ctx context.Context, policyID int64) ([]PolicyTrigger, error) {
	rows, err := q.db.Query(ctx, listPolicyTriggersByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyTrigger
	for rows.Next() {
		var i PolicyTrigger
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Type,
			&i.Branches,
			&i.Cron,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPolicyRepositoryTargets = `-- name: ListScheduledPolicyRepositoryTargets :many
SELECT
    p.user_id,
    p.id AS policy_id,
    pt.id AS trigger_id,
    pt.cron,
    pt.timezone,
    r.github_repo_id
FROM policies p
INNER JOIN policy_triggers pt ON pt.policy_id = p.id
INNER JOIN policy_repositories pr ON pr.policy_id = p.id
INNER JOIN repositories r ON r.id = pr.repository_id
WHERE p.enabled = TRUE
  AND pt.type = 'schedule'::trigger_type
ORDER BY p.id, pt.id, r.github_repo_id
`

type ListScheduledPolicyRepositoryTargetsRow struct {
	UserID       int64       `json:"user_id"`
	PolicyID     int64       `json:"policy_id"`
	TriggerID    int64       `json:"trigger_id"`
	Cron         pgtype.Text `json:"cron"`
	Timezone     string      `json:"timezone"`
	GithubRepoID int64       `json:"github_repo_id"`
}

func (q *Queries) ListScheduledPolicyRepositoryTargets(ctx context.Context) ([]ListScheduledPolicyRepositoryTargetsRow, error) {
	rows, err := q.db.Query(ctx, listScheduledPolicyRepositoryTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledPolicyRepositoryTargetsRow
	for rows.Next() {
		var i ListScheduledPolicyRepositoryTargetsRow
		if err := rows.Scan(
			&i.UserID,
			&i.PolicyID,
			&i.TriggerID,
			&i.Cron,
			&i.Timezone,
			&i.GithubRepoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPolicyEnabledByIDAndUser = `-- name: SetPolicyEnabledByIDAndUser :one
UPDATE policies
SET enabled = $3,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, enabled, created_at, updated_at
`

type SetPolicyEnabledByIDAndUserParams struct {
	ID      int64 `json:"id"`
	UserID  int64 `json:"user_id"`
	Enabled bool  `json:"enabled"`
}

func (q *Queries) SetPolicyEnabledByIDAndUser(ctx context.Context, arg SetPolicyEnabledByIDAndUserParams) (Policy, error) {
	row := q.db.QueryRow(ctx, setPolicyEnabledByIDAndUser, arg.ID, arg.UserID, arg.Enabled)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unassignPolicyFromRepository = `-- name: UnassignPolicyFromRepository :exec
DELETE FROM policy_repositories
WHERE repository_id = $1
`

func (q *Queries) UnassignPolicyFromRepository(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, unassignPolicyFromRepository, repositoryID)
	return err
}

const updatePolicyByIDAndUser = `-- name: UpdatePolicyByIDAndUser :one
UPDATE policies
SET name = $3,
    enabled = $4,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, name, enabled, created_at, updated_at
`

type UpdatePolicyByIDAndUserParams struct {
	ID      int64  `json:"id"`
	UserID  int64  `json:"user_id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdatePolicyByIDAndUser(ctx context.Context, arg UpdatePolicyByIDAndUserParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicyByIDAndUser,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Enabled,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPolicyRegistry = `-- name: UpsertPolicyRegistry :exec
INSERT INTO policy_registry (
    policy_id,
    push_enabled,
    push_url,
    push_signing_key_ref,
    pull_enabled,
    pull_url,
    pull_trusted_keys,
    pull_max_age_days
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (policy_id)
DO UPDATE SET
    push_enabled = EXCLUDED.push_enabled,
    push_url = EXCLUDED.push_url,
    push_signing_key_ref = EXCLUDED.push_signing_key_ref,
    pull_enabled = EXCLUDED.pull_enabled,
    pull_url = EXCLUDED.pull_url,
    pull_trusted_keys = EXCLUDED.pull_trusted_keys,
    pull_max_age_days = EXCLUDED.pull_max_age_days
`

type UpsertPolicyRegistryParams struct {
	PolicyID          int64    `json:"policy_id"`
	PushEnabled       bool     `json:"push_enabled"`
	PushUrl           string   `json:"push_url"`
	PushSigningKeyRef string   `json:"push_signing_key_ref"`
	PullEnabled       bool     `json:"pull_enabled"`
	PullUrl           string   `json:"pull_url"`
	PullTrustedKeys   []string `json:"pull_trusted_keys"`
	PullMaxAgeDays    int32    `json:"pull_max_age_days"`
}

func (q *Queries) UpsertPolicyRegistry(ctx context.Context, arg UpsertPolicyRegistryParams) error {
	_, err := q.db.Exec(ctx, upsertPolicyRegistry,
		arg.PolicyID,
		arg.PushEnabled,
		arg.PushUrl,
		arg.PushSigningKeyRef,
		arg.PullEnabled,
		arg.PullUrl,
		arg.PullTrustedKeys,
		arg.PullMaxAgeDays,
	)
	return err
}

const upsertPolicySast = `-- name: UpsertPolicySast :exec
INSERT INTO policy_sast (
    policy_id,
    enabled,
    patterns_enabled,
    rulesets,
    min_severity,
    exclude_paths,
    ai_enabled,
    ai_max_files_per_scan,
    ai_reachability,
    ai_suggest_fix
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (policy_id)
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    patterns_enabled = EXCLUDED.patterns_enabled,
    rulesets = EXCLUDED.rulesets,
    min_severity = EXCLUDED.min_severity,
    exclude_paths = EXCLUDED.exclude_paths,
    ai_enabled = EXCLUDED.ai_enabled,
    ai_max_files_per_scan = EXCLUDED.ai_max_files_per_scan,
    ai_reachability = EXCLUDED.ai_reachability,
    ai_suggest_fix = EXCLUDED.ai_suggest_fix
`

type UpsertPolicySastParams struct {
	PolicyID          int64    `json:"policy_id"`
	Enabled           bool     `json:"enabled"`
	PatternsEnabled   bool     `json:"patterns_enabled"`
	Rulesets          []string `json:"rulesets"`
	MinSeverity       Severity `json:"min_severity"`
	ExcludePaths      []string `json:"exclude_paths"`
	AiEnabled         bool     `json:"ai_enabled"`
	AiMaxFilesPerScan int32    `json:"ai_max_files_per_scan"`
	AiReachability    bool     `json:"ai_reachability"`
	AiSuggestFix      bool     `json:"ai_suggest_fix"`
}

func (q *Queries) UpsertPolicySast(ctx context.Context, arg UpsertPolicySastParams) error {
	_, err := q.db.Exec(ctx, upsertPolicySast,
		arg.PolicyID,
		arg.Enabled,
		arg.PatternsEnabled,
		arg.Rulesets,
		arg.MinSeverity,
		arg.ExcludePaths,
		arg.AiEnabled,
		arg.AiMaxFilesPerScan,
		arg.AiReachability,
		arg.AiSuggestFix,
	)
	return err
}

const upsertPolicySources = `-- name: UpsertPolicySources :exec
INSERT INTO policy_sources (
    policy_id,
    registry_first,
    registry_max_age_days,
    registry_only,
    osv_enabled,
    ghsa_enabled,
    ghsa_token_ref,
    nvd_enabled,
    nvd_api_key_ref,
    govulncheck_enabled,
    supply_chain_enabled
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (policy_id)
DO UPDATE SET
    registry_first = EXCLUDED.registry_first,
    registry_max_age_days = EXCLUDED.registry_max_age_days,
    registry_only = EXCLUDED.registry_only,
    osv_enabled = EXCLUDED.osv_enabled,
    ghsa_enabled = EXCLUDED.ghsa_enabled,
    ghsa_token_ref = EXCLUDED.ghsa_token_ref,
    nvd_enabled = EXCLUDED.nvd_enabled,
    nvd_api_key_ref = EXCLUDED.nvd_api_key_ref,
    govulncheck_enabled = EXCLUDED.govulncheck_enabled,
    supply_chain_enabled = EXCLUDED.supply_chain_enabled
`

type UpsertPolicySourcesParams struct {
	PolicyID           int64  `json:"policy_id"`
	RegistryFirst      bool   `json:"registry_first"`
	RegistryMaxAgeDays int32  `json:"registry_max_age_days"`
	RegistryOnly       bool   `json:"registry_only"`
	OsvEnabled         bool   `json:"osv_enabled"`
	GhsaEnabled        bool   `json:"ghsa_enabled"`
	GhsaTokenRef       string `json:"ghsa_token_ref"`
	NvdEnabled         bool   `json:"nvd_enabled"`
	NvdApiKeyRef       string `json:"nvd_api_key_ref"`
	GovulncheckEnabled bool   `json:"govulncheck_enabled"`
	SupplyChainEnabled bool   `json:"supply_chain_enabled"`
}

func (q *Queries) UpsertPolicySources(ctx context.Context, arg UpsertPolicySourcesParams) error {
	_, err := q.db.Exec(ctx, upsertPolicySources,
		arg.PolicyID,
		arg.RegistryFirst,
		arg.RegistryMaxAgeDays,
		arg.RegistryOnly,
		arg.OsvEnabled,
		arg.GhsaEnabled,
		arg.GhsaTokenRef,
		arg.NvdEnabled,
		arg.NvdApiKeyRef,
		arg.GovulncheckEnabled,
		arg.SupplyChainEnabled,
	)
	return err
}
