// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRepositoryScanFindingSource = `-- name: AddRepositoryScanFindingSource :exec
INSERT INTO repository_scan_finding_sources (
    finding_id,
    source,
    provider_record_id
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (finding_id, source)
DO UPDATE SET
    provider_record_id = EXCLUDED.provider_record_id
`

type AddRepositoryScanFindingSourceParams struct {
	FindingID        int64  `json:"finding_id"`
	Source           string `json:"source"`
	ProviderRecordID string `json:"provider_record_id"`
}

func (q *Queries) AddRepositoryScanFindingSource(ctx context.Context, arg AddRepositoryScanFindingSourceParams) error {
	_, err := q.db.Exec(ctx, addRepositoryScanFindingSource, arg.FindingID, arg.Source, arg.ProviderRecordID)
	return err
}

const countRepositoryScansByStatus = `-- name: CountRepositoryScansByStatus :one
SELECT COUNT(*)::BIGINT
FROM repository_scan_runs
WHERE status = $1
`

func (q *Queries) CountRepositoryScansByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryScansByStatus, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRepositoryScansFailedSince = `-- name: CountRepositoryScansFailedSince :one
SELECT COUNT(*)::BIGINT
FROM repository_scan_runs
WHERE status = 'failed'
  AND finished_at >= $1
`

func (q *Queries) CountRepositoryScansFailedSince(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryScansFailedSince, finishedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRepositoryScansSuccessSince = `-- name: CountRepositoryScansSuccessSince :one
SELECT COUNT(*)::BIGINT
FROM repository_scan_runs
WHERE status = 'success'
  AND finished_at >= $1
`

func (q *Queries) CountRepositoryScansSuccessSince(ctx context.Context, finishedAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryScansSuccessSince, finishedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRepositoryScanFinding = `-- name: CreateRepositoryScanFinding :one
INSERT INTO repository_scan_findings (
    scan_run_id,
    repository_id,
    policy_id,
    package_id,
    package_name,
    manager,
    registry,
    version_spec,
    resolved_version,
    advisory_id,
    aliases,
    title,
    summary,
    severity,
    fixed_version,
    reference_url,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    'open'
)
ON CONFLICT (scan_run_id, package_name, advisory_id)
DO UPDATE SET
    policy_id = EXCLUDED.policy_id,
    package_id = EXCLUDED.package_id,
    manager = EXCLUDED.manager,
    registry = EXCLUDED.registry,
    version_spec = EXCLUDED.version_spec,
    resolved_version = EXCLUDED.resolved_version,
    aliases = EXCLUDED.aliases,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    severity = EXCLUDED.severity,
    fixed_version = EXCLUDED.fixed_version,
    reference_url = EXCLUDED.reference_url,
    status = 'open',
    updated_at = NOW()
RETURNING id, scan_run_id, repository_id, policy_id, package_id, package_name, manager, registry, version_spec, resolved_version, advisory_id, aliases, title, summary, severity, fixed_version, reference_url, status, created_at, updated_at
`

type CreateRepositoryScanFindingParams struct {
	ScanRunID       int64       `json:"scan_run_id"`
	RepositoryID    int64       `json:"repository_id"`
	PolicyID        pgtype.Int8 `json:"policy_id"`
	PackageID       pgtype.Int8 `json:"package_id"`
	PackageName     string      `json:"package_name"`
	Manager         string      `json:"manager"`
	Registry        string      `json:"registry"`
	VersionSpec     string      `json:"version_spec"`
	ResolvedVersion string      `json:"resolved_version"`
	AdvisoryID      string      `json:"advisory_id"`
	Aliases         []string    `json:"aliases"`
	Title           string      `json:"title"`
	Summary         string      `json:"summary"`
	Severity        Severity    `json:"severity"`
	FixedVersion    string      `json:"fixed_version"`
	ReferenceUrl    string      `json:"reference_url"`
}

func (q *Queries) CreateRepositoryScanFinding(ctx context.Context, arg CreateRepositoryScanFindingParams) (RepositoryScanFinding, error) {
	row := q.db.QueryRow(ctx, createRepositoryScanFinding,
		arg.ScanRunID,
		arg.RepositoryID,
		arg.PolicyID,
		arg.PackageID,
		arg.PackageName,
		arg.Manager,
		arg.Registry,
		arg.VersionSpec,
		arg.ResolvedVersion,
		arg.AdvisoryID,
		arg.Aliases,
		arg.Title,
		arg.Summary,
		arg.Severity,
		arg.FixedVersion,
		arg.ReferenceUrl,
	)
	var i RepositoryScanFinding
	err := row.Scan(
		&i.ID,
		&i.ScanRunID,
		&i.RepositoryID,
		&i.PolicyID,
		&i.PackageID,
		&i.PackageName,
		&i.Manager,
		&i.Registry,
		&i.VersionSpec,
		&i.ResolvedVersion,
		&i.AdvisoryID,
		&i.Aliases,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.FixedVersion,
		&i.ReferenceUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRepositoryScanLog = `-- name: CreateRepositoryScanLog :exec
INSERT INTO repository_scan_logs (
    scan_run_id,
    repository_id,
    level,
    message,
    directory_path
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateRepositoryScanLogParams struct {
	ScanRunID     int64  `json:"scan_run_id"`
	RepositoryID  int64  `json:"repository_id"`
	Level         string `json:"level"`
	Message       string `json:"message"`
	DirectoryPath string `json:"directory_path"`
}

func (q *Queries) CreateRepositoryScanLog(ctx context.Context, arg CreateRepositoryScanLogParams) error {
	_, err := q.db.Exec(ctx, createRepositoryScanLog,
		arg.ScanRunID,
		arg.RepositoryID,
		arg.Level,
		arg.Message,
		arg.DirectoryPath,
	)
	return err
}

const createRepositoryScanRun = `-- name: CreateRepositoryScanRun :one
INSERT INTO repository_scan_runs (
    repository_id,
    policy_id,
    trigger,
    status,
    error_message,
    started_at,
    finished_at,
    findings_total,
    findings_critical,
    findings_high,
    findings_medium,
    findings_low
) VALUES (
    $1,
    $2,
    $3,
    'queued',
    '',
    NOW(),
    NULL,
    0,
    0,
    0,
    0,
    0
)
RETURNING id, repository_id, policy_id, trigger, status, error_message, findings_total, findings_critical, findings_high, findings_medium, findings_low, started_at, finished_at, created_at, updated_at
`

type CreateRepositoryScanRunParams struct {
	RepositoryID int64       `json:"repository_id"`
	PolicyID     pgtype.Int8 `json:"policy_id"`
	Trigger      string      `json:"trigger"`
}

func (q *Queries) CreateRepositoryScanRun(ctx context.Context, arg CreateRepositoryScanRunParams) (RepositoryScanRun, error) {
	row := q.db.QueryRow(ctx, createRepositoryScanRun, arg.RepositoryID, arg.PolicyID, arg.Trigger)
	var i RepositoryScanRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.PolicyID,
		&i.Trigger,
		&i.Status,
		&i.ErrorMessage,
		&i.FindingsTotal,
		&i.FindingsCritical,
		&i.FindingsHigh,
		&i.FindingsMedium,
		&i.FindingsLow,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingByIDAndUser = `-- name: GetFindingByIDAndUser :one
SELECT
    f.id,
    f.scan_run_id,
    f.repository_id,
    r.full_name AS repository_full_name,
    COALESCE(p.name, '') AS policy_name,
    f.package_name,
    f.manager,
    f.registry,
    f.version_spec,
    f.resolved_version,
    f.advisory_id,
    f.aliases,
    f.title,
    f.summary,
    f.severity,
    f.fixed_version,
    f.reference_url,
    f.status,
    COALESCE((
        SELECT ARRAY_AGG(src.source ORDER BY src.source)
        FROM (
            SELECT DISTINCT fs2.source
            FROM repository_scan_finding_sources fs2
            WHERE fs2.finding_id = f.id
        ) AS src
    ), ARRAY[]::TEXT[])::TEXT[] AS sources,
    f.created_at,
    f.updated_at
FROM repository_scan_findings f
INNER JOIN repository_scan_runs s ON s.id = f.scan_run_id
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
LEFT JOIN policies p ON p.id = f.policy_id
WHERE r.user_id = $1
  AND f.id = $2
GROUP BY
    f.id,
    f.scan_run_id,
    f.repository_id,
    r.full_name,
    p.name,
    f.package_name,
    f.manager,
    f.registry,
    f.version_spec,
    f.resolved_version,
    f.advisory_id,
    f.aliases,
    f.title,
    f.summary,
    f.severity,
    f.fixed_version,
    f.reference_url,
    f.status,
    f.created_at,
    f.updated_at
`

type GetFindingByIDAndUserParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type GetFindingByIDAndUserRow struct {
	ID                 int64              `json:"id"`
	ScanRunID          int64              `json:"scan_run_id"`
	RepositoryID       int64              `json:"repository_id"`
	RepositoryFullName string             `json:"repository_full_name"`
	PolicyName         string             `json:"policy_name"`
	PackageName        string             `json:"package_name"`
	Manager            string             `json:"manager"`
	Registry           string             `json:"registry"`
	VersionSpec        string             `json:"version_spec"`
	ResolvedVersion    string             `json:"resolved_version"`
	AdvisoryID         string             `json:"advisory_id"`
	Aliases            []string           `json:"aliases"`
	Title              string             `json:"title"`
	Summary            string             `json:"summary"`
	Severity           Severity           `json:"severity"`
	FixedVersion       string             `json:"fixed_version"`
	ReferenceUrl       string             `json:"reference_url"`
	Status             string             `json:"status"`
	Sources            []string           `json:"sources"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFindingByIDAndUser(ctx context.Context, arg GetFindingByIDAndUserParams) (GetFindingByIDAndUserRow, error) {
	row := q.db.QueryRow(ctx, getFindingByIDAndUser, arg.UserID, arg.ID)
	var i GetFindingByIDAndUserRow
	err := row.Scan(
		&i.ID,
		&i.ScanRunID,
		&i.RepositoryID,
		&i.RepositoryFullName,
		&i.PolicyName,
		&i.PackageName,
		&i.Manager,
		&i.Registry,
		&i.VersionSpec,
		&i.ResolvedVersion,
		&i.AdvisoryID,
		&i.Aliases,
		&i.Title,
		&i.Summary,
		&i.Severity,
		&i.FixedVersion,
		&i.ReferenceUrl,
		&i.Status,
		&i.Sources,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryScanRunByIDAndUser = `-- name: GetRepositoryScanRunByIDAndUser :one
SELECT
    s.id,
    s.repository_id,
    r.full_name AS repository_full_name,
    COALESCE(p.name, '') AS policy_name,
    s.policy_id,
    s.trigger,
    s.status,
    s.error_message,
    s.findings_total,
    s.findings_critical,
    s.findings_high,
    s.findings_medium,
    s.findings_low,
    s.started_at,
    s.finished_at,
    s.created_at,
    s.updated_at
FROM repository_scan_runs s
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
LEFT JOIN policies p ON p.id = s.policy_id
WHERE r.user_id = $1
  AND s.id = $2
`

type GetRepositoryScanRunByIDAndUserParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type GetRepositoryScanRunByIDAndUserRow struct {
	ID                 int64              `json:"id"`
	RepositoryID       int64              `json:"repository_id"`
	RepositoryFullName string             `json:"repository_full_name"`
	PolicyName         string             `json:"policy_name"`
	PolicyID           pgtype.Int8        `json:"policy_id"`
	Trigger            string             `json:"trigger"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	FindingsTotal      int32              `json:"findings_total"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRepositoryScanRunByIDAndUser(ctx context.Context, arg GetRepositoryScanRunByIDAndUserParams) (GetRepositoryScanRunByIDAndUserRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryScanRunByIDAndUser, arg.UserID, arg.ID)
	var i GetRepositoryScanRunByIDAndUserRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.RepositoryFullName,
		&i.PolicyName,
		&i.PolicyID,
		&i.Trigger,
		&i.Status,
		&i.ErrorMessage,
		&i.FindingsTotal,
		&i.FindingsCritical,
		&i.FindingsHigh,
		&i.FindingsMedium,
		&i.FindingsLow,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFindingsByUser = `-- name: ListFindingsByUser :many
SELECT
    f.id,
    f.scan_run_id,
    f.repository_id,
    r.full_name AS repository_full_name,
    COALESCE(p.name, '') AS policy_name,
    f.package_name,
    f.manager,
    f.registry,
    f.version_spec,
    f.resolved_version,
    f.advisory_id,
    f.aliases,
    f.title,
    f.summary,
    f.severity,
    f.fixed_version,
    f.reference_url,
    f.status,
    COALESCE((
        SELECT ARRAY_AGG(src.source ORDER BY src.source)
        FROM (
            SELECT DISTINCT fs2.source
            FROM repository_scan_finding_sources fs2
            WHERE fs2.finding_id = f.id
        ) AS src
    ), ARRAY[]::TEXT[])::TEXT[] AS sources,
    f.created_at,
    f.updated_at
FROM repository_scan_findings f
INNER JOIN repository_scan_runs s ON s.id = f.scan_run_id
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
LEFT JOIN policies p ON p.id = f.policy_id
WHERE r.user_id = $1
GROUP BY
    f.id,
    f.scan_run_id,
    f.repository_id,
    r.full_name,
    p.name,
    f.package_name,
    f.manager,
    f.registry,
    f.version_spec,
    f.resolved_version,
    f.advisory_id,
    f.aliases,
    f.title,
    f.summary,
    f.severity,
    f.fixed_version,
    f.reference_url,
    f.status,
    f.created_at,
    f.updated_at
ORDER BY f.created_at DESC, f.id DESC
`

type ListFindingsByUserRow struct {
	ID                 int64              `json:"id"`
	ScanRunID          int64              `json:"scan_run_id"`
	RepositoryID       int64              `json:"repository_id"`
	RepositoryFullName string             `json:"repository_full_name"`
	PolicyName         string             `json:"policy_name"`
	PackageName        string             `json:"package_name"`
	Manager            string             `json:"manager"`
	Registry           string             `json:"registry"`
	VersionSpec        string             `json:"version_spec"`
	ResolvedVersion    string             `json:"resolved_version"`
	AdvisoryID         string             `json:"advisory_id"`
	Aliases            []string           `json:"aliases"`
	Title              string             `json:"title"`
	Summary            string             `json:"summary"`
	Severity           Severity           `json:"severity"`
	FixedVersion       string             `json:"fixed_version"`
	ReferenceUrl       string             `json:"reference_url"`
	Status             string             `json:"status"`
	Sources            []string           `json:"sources"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFindingsByUser(ctx context.Context, userID int64) ([]ListFindingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listFindingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsByUserRow
	for rows.Next() {
		var i ListFindingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ScanRunID,
			&i.RepositoryID,
			&i.RepositoryFullName,
			&i.PolicyName,
			&i.PackageName,
			&i.Manager,
			&i.Registry,
			&i.VersionSpec,
			&i.ResolvedVersion,
			&i.AdvisoryID,
			&i.Aliases,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.FixedVersion,
			&i.ReferenceUrl,
			&i.Status,
			&i.Sources,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestRepositoryFindingSourcesByRepoAndUser = `-- name: ListLatestRepositoryFindingSourcesByRepoAndUser :many
WITH latest AS (
    SELECT s.id
    FROM repository_scan_runs s
    INNER JOIN repositories r ON r.github_repo_id = s.repository_id
    WHERE r.user_id = $1
      AND s.repository_id = $2
      AND s.status IN ('success', 'failed')
    ORDER BY s.started_at DESC
    LIMIT 1
)
SELECT
    fs.finding_id,
    fs.source,
    fs.provider_record_id
FROM repository_scan_finding_sources fs
INNER JOIN repository_scan_findings f ON f.id = fs.finding_id
INNER JOIN latest ON latest.id = f.scan_run_id
ORDER BY fs.finding_id, fs.source
`

type ListLatestRepositoryFindingSourcesByRepoAndUserParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

type ListLatestRepositoryFindingSourcesByRepoAndUserRow struct {
	FindingID        int64  `json:"finding_id"`
	Source           string `json:"source"`
	ProviderRecordID string `json:"provider_record_id"`
}

func (q *Queries) ListLatestRepositoryFindingSourcesByRepoAndUser(ctx context.Context, arg ListLatestRepositoryFindingSourcesByRepoAndUserParams) ([]ListLatestRepositoryFindingSourcesByRepoAndUserRow, error) {
	rows, err := q.db.Query(ctx, listLatestRepositoryFindingSourcesByRepoAndUser, arg.UserID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestRepositoryFindingSourcesByRepoAndUserRow
	for rows.Next() {
		var i ListLatestRepositoryFindingSourcesByRepoAndUserRow
		if err := rows.Scan(&i.FindingID, &i.Source, &i.ProviderRecordID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestRepositoryFindingsByRepoAndUser = `-- name: ListLatestRepositoryFindingsByRepoAndUser :many
WITH latest AS (
    SELECT s.id
    FROM repository_scan_runs s
    INNER JOIN repositories r ON r.github_repo_id = s.repository_id
    WHERE r.user_id = $1
      AND s.repository_id = $2
      AND s.status IN ('success', 'failed')
    ORDER BY s.started_at DESC
    LIMIT 1
)
SELECT
    f.id,
    f.scan_run_id,
    f.repository_id,
    f.policy_id,
    f.package_id,
    f.package_name,
    f.manager,
    f.registry,
    f.version_spec,
    f.resolved_version,
    f.advisory_id,
    f.aliases,
    f.title,
    f.summary,
    f.severity,
    f.fixed_version,
    f.reference_url,
    f.status,
    f.created_at,
    f.updated_at
FROM repository_scan_findings f
INNER JOIN latest ON latest.id = f.scan_run_id
ORDER BY f.severity DESC, f.package_name ASC
`

type ListLatestRepositoryFindingsByRepoAndUserParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

func (q *Queries) ListLatestRepositoryFindingsByRepoAndUser(ctx context.Context, arg ListLatestRepositoryFindingsByRepoAndUserParams) ([]RepositoryScanFinding, error) {
	rows, err := q.db.Query(ctx, listLatestRepositoryFindingsByRepoAndUser, arg.UserID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryScanFinding
	for rows.Next() {
		var i RepositoryScanFinding
		if err := rows.Scan(
			&i.ID,
			&i.ScanRunID,
			&i.RepositoryID,
			&i.PolicyID,
			&i.PackageID,
			&i.PackageName,
			&i.Manager,
			&i.Registry,
			&i.VersionSpec,
			&i.ResolvedVersion,
			&i.AdvisoryID,
			&i.Aliases,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.FixedVersion,
			&i.ReferenceUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestRepositoryScanRunByRepo = `-- name: ListLatestRepositoryScanRunByRepo :many
SELECT id, repository_id, policy_id, trigger, status, error_message, findings_total, findings_critical, findings_high, findings_medium, findings_low, started_at, finished_at, created_at, updated_at
FROM repository_scan_runs
WHERE repository_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) ListLatestRepositoryScanRunByRepo(ctx context.Context, repositoryID int64) ([]RepositoryScanRun, error) {
	rows, err := q.db.Query(ctx, listLatestRepositoryScanRunByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryScanRun
	for rows.Next() {
		var i RepositoryScanRun
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.PolicyID,
			&i.Trigger,
			&i.Status,
			&i.ErrorMessage,
			&i.FindingsTotal,
			&i.FindingsCritical,
			&i.FindingsHigh,
			&i.FindingsMedium,
			&i.FindingsLow,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryScanFindingSourcesByRunAndUser = `-- name: ListRepositoryScanFindingSourcesByRunAndUser :many
SELECT
    fs.finding_id,
    fs.source,
    fs.provider_record_id
FROM repository_scan_finding_sources fs
INNER JOIN repository_scan_findings f ON f.id = fs.finding_id
INNER JOIN repository_scan_runs s ON s.id = f.scan_run_id
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
WHERE r.user_id = $1
  AND s.id = $2
ORDER BY fs.finding_id, fs.source
`

type ListRepositoryScanFindingSourcesByRunAndUserParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type ListRepositoryScanFindingSourcesByRunAndUserRow struct {
	FindingID        int64  `json:"finding_id"`
	Source           string `json:"source"`
	ProviderRecordID string `json:"provider_record_id"`
}

func (q *Queries) ListRepositoryScanFindingSourcesByRunAndUser(ctx context.Context, arg ListRepositoryScanFindingSourcesByRunAndUserParams) ([]ListRepositoryScanFindingSourcesByRunAndUserRow, error) {
	rows, err := q.db.Query(ctx, listRepositoryScanFindingSourcesByRunAndUser, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepositoryScanFindingSourcesByRunAndUserRow
	for rows.Next() {
		var i ListRepositoryScanFindingSourcesByRunAndUserRow
		if err := rows.Scan(&i.FindingID, &i.Source, &i.ProviderRecordID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryScanFindingsByRunAndUser = `-- name: ListRepositoryScanFindingsByRunAndUser :many
SELECT
    f.id,
    f.scan_run_id,
    f.repository_id,
    f.policy_id,
    f.package_id,
    f.package_name,
    f.manager,
    f.registry,
    f.version_spec,
    f.resolved_version,
    f.advisory_id,
    f.aliases,
    f.title,
    f.summary,
    f.severity,
    f.fixed_version,
    f.reference_url,
    f.status,
    f.created_at,
    f.updated_at
FROM repository_scan_findings f
INNER JOIN repository_scan_runs s ON s.id = f.scan_run_id
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
WHERE r.user_id = $1
  AND f.scan_run_id = $2
ORDER BY f.severity DESC, f.package_name ASC
`

type ListRepositoryScanFindingsByRunAndUserParams struct {
	UserID    int64 `json:"user_id"`
	ScanRunID int64 `json:"scan_run_id"`
}

func (q *Queries) ListRepositoryScanFindingsByRunAndUser(ctx context.Context, arg ListRepositoryScanFindingsByRunAndUserParams) ([]RepositoryScanFinding, error) {
	rows, err := q.db.Query(ctx, listRepositoryScanFindingsByRunAndUser, arg.UserID, arg.ScanRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryScanFinding
	for rows.Next() {
		var i RepositoryScanFinding
		if err := rows.Scan(
			&i.ID,
			&i.ScanRunID,
			&i.RepositoryID,
			&i.PolicyID,
			&i.PackageID,
			&i.PackageName,
			&i.Manager,
			&i.Registry,
			&i.VersionSpec,
			&i.ResolvedVersion,
			&i.AdvisoryID,
			&i.Aliases,
			&i.Title,
			&i.Summary,
			&i.Severity,
			&i.FixedVersion,
			&i.ReferenceUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryScanLogsByRunAndUser = `-- name: ListRepositoryScanLogsByRunAndUser :many
SELECT
    l.id,
    l.scan_run_id,
    l.repository_id,
    l.level,
    l.message,
    l.directory_path,
    l.created_at
FROM repository_scan_logs l
INNER JOIN repository_scan_runs s ON s.id = l.scan_run_id
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
WHERE r.user_id = $1
  AND l.scan_run_id = $2
ORDER BY l.created_at ASC, l.id ASC
`

type ListRepositoryScanLogsByRunAndUserParams struct {
	UserID    int64 `json:"user_id"`
	ScanRunID int64 `json:"scan_run_id"`
}

func (q *Queries) ListRepositoryScanLogsByRunAndUser(ctx context.Context, arg ListRepositoryScanLogsByRunAndUserParams) ([]RepositoryScanLog, error) {
	rows, err := q.db.Query(ctx, listRepositoryScanLogsByRunAndUser, arg.UserID, arg.ScanRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryScanLog
	for rows.Next() {
		var i RepositoryScanLog
		if err := rows.Scan(
			&i.ID,
			&i.ScanRunID,
			&i.RepositoryID,
			&i.Level,
			&i.Message,
			&i.DirectoryPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryScanRunsByRepoAndUser = `-- name: ListRepositoryScanRunsByRepoAndUser :many
SELECT
    s.id,
    s.repository_id,
    r.full_name AS repository_full_name,
    COALESCE(p.name, '') AS policy_name,
    s.policy_id,
    s.trigger,
    s.status,
    s.error_message,
    s.findings_total,
    s.findings_critical,
    s.findings_high,
    s.findings_medium,
    s.findings_low,
    s.started_at,
    s.finished_at,
    s.created_at,
    s.updated_at
FROM repository_scan_runs s
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
LEFT JOIN policies p ON p.id = s.policy_id
WHERE r.user_id = $1
  AND s.repository_id = $2
ORDER BY s.started_at DESC
`

type ListRepositoryScanRunsByRepoAndUserParams struct {
	UserID       int64 `json:"user_id"`
	RepositoryID int64 `json:"repository_id"`
}

type ListRepositoryScanRunsByRepoAndUserRow struct {
	ID                 int64              `json:"id"`
	RepositoryID       int64              `json:"repository_id"`
	RepositoryFullName string             `json:"repository_full_name"`
	PolicyName         string             `json:"policy_name"`
	PolicyID           pgtype.Int8        `json:"policy_id"`
	Trigger            string             `json:"trigger"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	FindingsTotal      int32              `json:"findings_total"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRepositoryScanRunsByRepoAndUser(ctx context.Context, arg ListRepositoryScanRunsByRepoAndUserParams) ([]ListRepositoryScanRunsByRepoAndUserRow, error) {
	rows, err := q.db.Query(ctx, listRepositoryScanRunsByRepoAndUser, arg.UserID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepositoryScanRunsByRepoAndUserRow
	for rows.Next() {
		var i ListRepositoryScanRunsByRepoAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.RepositoryFullName,
			&i.PolicyName,
			&i.PolicyID,
			&i.Trigger,
			&i.Status,
			&i.ErrorMessage,
			&i.FindingsTotal,
			&i.FindingsCritical,
			&i.FindingsHigh,
			&i.FindingsMedium,
			&i.FindingsLow,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryScanRunsByUser = `-- name: ListRepositoryScanRunsByUser :many
SELECT
    s.id,
    s.repository_id,
    r.full_name AS repository_full_name,
    COALESCE(p.name, '') AS policy_name,
    s.policy_id,
    s.trigger,
    s.status,
    s.error_message,
    s.findings_total,
    s.findings_critical,
    s.findings_high,
    s.findings_medium,
    s.findings_low,
    s.started_at,
    s.finished_at,
    s.created_at,
    s.updated_at
FROM repository_scan_runs s
INNER JOIN repositories r ON r.github_repo_id = s.repository_id
LEFT JOIN policies p ON p.id = s.policy_id
WHERE r.user_id = $1
ORDER BY s.started_at DESC
`

type ListRepositoryScanRunsByUserRow struct {
	ID                 int64              `json:"id"`
	RepositoryID       int64              `json:"repository_id"`
	RepositoryFullName string             `json:"repository_full_name"`
	PolicyName         string             `json:"policy_name"`
	PolicyID           pgtype.Int8        `json:"policy_id"`
	Trigger            string             `json:"trigger"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	FindingsTotal      int32              `json:"findings_total"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRepositoryScanRunsByUser(ctx context.Context, userID int64) ([]ListRepositoryScanRunsByUserRow, error) {
	rows, err := q.db.Query(ctx, listRepositoryScanRunsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepositoryScanRunsByUserRow
	for rows.Next() {
		var i ListRepositoryScanRunsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.RepositoryFullName,
			&i.PolicyName,
			&i.PolicyID,
			&i.Trigger,
			&i.Status,
			&i.ErrorMessage,
			&i.FindingsTotal,
			&i.FindingsCritical,
			&i.FindingsHigh,
			&i.FindingsMedium,
			&i.FindingsLow,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepositoryScanRunFailed = `-- name: MarkRepositoryScanRunFailed :exec
UPDATE repository_scan_runs
SET status = 'failed',
    error_message = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkRepositoryScanRunFailedParams struct {
	ID           int64  `json:"id"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) MarkRepositoryScanRunFailed(ctx context.Context, arg MarkRepositoryScanRunFailedParams) error {
	_, err := q.db.Exec(ctx, markRepositoryScanRunFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markRepositoryScanRunRunning = `-- name: MarkRepositoryScanRunRunning :exec
UPDATE repository_scan_runs
SET status = 'running',
    error_message = '',
    started_at = NOW(),
    finished_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRepositoryScanRunRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRepositoryScanRunRunning, id)
	return err
}

const markRepositoryScanRunSuccess = `-- name: MarkRepositoryScanRunSuccess :exec
UPDATE repository_scan_runs
SET status = 'success',
    error_message = '',
    findings_total = $2,
    findings_critical = $3,
    findings_high = $4,
    findings_medium = $5,
    findings_low = $6,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkRepositoryScanRunSuccessParams struct {
	ID               int64 `json:"id"`
	FindingsTotal    int32 `json:"findings_total"`
	FindingsCritical int32 `json:"findings_critical"`
	FindingsHigh     int32 `json:"findings_high"`
	FindingsMedium   int32 `json:"findings_medium"`
	FindingsLow      int32 `json:"findings_low"`
}

func (q *Queries) MarkRepositoryScanRunSuccess(ctx context.Context, arg MarkRepositoryScanRunSuccessParams) error {
	_, err := q.db.Exec(ctx, markRepositoryScanRunSuccess,
		arg.ID,
		arg.FindingsTotal,
		arg.FindingsCritical,
		arg.FindingsHigh,
		arg.FindingsMedium,
		arg.FindingsLow,
	)
	return err
}
